name: Test Lambda Permissions (Static Keys)

on:
  workflow_dispatch:

env:
  AWS_REGION: "ap-south-1"
  LAMBDA_FUNCTION: "bash-runtime"

jobs:
  test-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (manual export)
        run: |
          export AWS_ACCESS_KEY_ID="$(echo "${{ secrets.AWS_ACCESS_KEY_ID }}" | tr -d '\n' | tr -d '\r')"
          export AWS_SECRET_ACCESS_KEY="$(echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}" | tr -d '\n' | tr -d '\r')"
          export AWS_SESSION_TOKEN="$(echo "${{ secrets.AWS_SESSION_TOKEN }}" | tr -d '\n' | tr -d '\r')"
          aws sts get-caller-identity



      # ✅ Allowed action
      - name: Allowed - Get Function
        run: |
          aws lambda get-function --function-name ${{ env.LAMBDA_FUNCTION }} || echo "GetFunction failed"

      # 🚫 Denied action
      - name: Denied - Delete Function
        run: |
          set +e
          aws lambda delete-function --function-name ${{ env.LAMBDA_FUNCTION }}
          if [ $? -eq 0 ]; then
            echo "❌ ERROR: DeleteFunction was ALLOWED (should be denied)"
            exit 1
          else
            echo "✅ DeleteFunction was DENIED as expected"
          fi
