name: Test Lambda Permissions (Static Keys)

on:
  workflow_dispatch:

env:
  AWS_REGION: "ap-south-1"
  LAMBDA_FUNCTION: "test1-aws-sdk"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  test-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: arn:aws:iam::607122710341:role/app-server-cicd-pipeline-role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ap-south-1
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: aws sts get-caller-identity

      # ✅ Allowed action
      - name: Allowed - Get Function
        run: |
          aws lambda get-function --function-name ${{ env.LAMBDA_FUNCTION }} || echo "GetFunction failed"

      # 🚫 Denied action
      - name: Denied - Delete Function
        run: |
          set +e
          aws lambda delete-function --function-name ${{ env.LAMBDA_FUNCTION }}
          if [ $? -eq 0 ]; then
            echo "❌ ERROR: DeleteFunction was ALLOWED (should be denied)"
            exit 1
          else
            echo "✅ DeleteFunction was DENIED as expected"
          fi
